### ISSUE TITLE
Security: what's the best way to disclose an issue?

### ISSUE THREAD

**Issue by almndbtr** [catalogworks/catalog-contracts#17]
👋  Hi Catalog Works!

Pending a contributing guide in this repo, I'm wondering -- what's the best way to disclose any security issues for this repository? 💭 

cc: [`GitHub Docs`: About disclosing vulnerabilities in the industry | Best practices for maintainers](https://docs.github.com/en/code-security/repository-security-advisories/about-coordinated-disclosure-of-security-vulnerabilities#best-practices-for-maintainers)

**Comment by bretth18** [comment]
hey @almndbtr !

i setup a document on security disclosures [here](https://github.com/catalogworks/catalog-contracts/blob/main/SECURITY.md)

as author/maintainer of this contract and repository, you can always reach out to me via [email](mailto:b@catalog.works) (or any preferred channels, like discord) to report **any** potential vulnerabilities.
